2020-02-23 16:00:16,412 - [testlogin.py-->line:43]- ERROR: 用例不通过
2020-02-23 16:00:16,412 - [testlogin.py-->line:44]- ERROR: {'cod[13 chars] 'OK'} != {'cod[13 chars] 'OK', 'data': {'id': 70915, 'leave_amount': 1[428 chars]ved'}
Diff is 662 characters long. Set self.maxDiff to None to see it.
Traceback (most recent call last):
  File "E:\project\apitest\testcases\testlogin.py", line 40, in test_login
    self.assertEqual(expected, res)
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 1138, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: {'cod[13 chars] 'OK'} != {'cod[13 chars] 'OK', 'data': {'id': 70915, 'leave_amount': 1[428 chars]ved'}
Diff is 662 characters long. Set self.maxDiff to None to see it.
2020-02-23 16:00:16,480 - [testlogin.py-->line:43]- ERROR: 用例不通过
2020-02-23 16:00:16,480 - [testlogin.py-->line:44]- ERROR: {'code': 1, 'msg': '手机号码为空'} != {'code': 2, 'msg': '手机号码为空', 'data': None, 'copyri[63 chars]ved'}
+ {'code': 2,
+  'copyright': 'Copyright 柠檬班 © 2017-2019 湖南省零檬信息技术有限公司 All Rights Reserved',
+  'data': None,
- {'code': 1, 'msg': '手机号码为空'}
? -----------

+  'msg': '手机号码为空'}
Traceback (most recent call last):
  File "E:\project\apitest\testcases\testlogin.py", line 40, in test_login
    self.assertEqual(expected, res)
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 1138, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: {'code': 1, 'msg': '手机号码为空'} != {'code': 2, 'msg': '手机号码为空', 'data': None, 'copyri[63 chars]ved'}
+ {'code': 2,
+  'copyright': 'Copyright 柠檬班 © 2017-2019 湖南省零檬信息技术有限公司 All Rights Reserved',
+  'data': None,
- {'code': 1, 'msg': '手机号码为空'}
? -----------

+  'msg': '手机号码为空'}
2020-02-23 16:00:16,539 - [testlogin.py-->line:43]- ERROR: 用例不通过
2020-02-23 16:00:16,540 - [testlogin.py-->line:44]- ERROR: {'code': 1, 'msg': '密码为空'} != {'code': 2, 'msg': '密码为空', 'data': None, 'copyrigh[61 chars]ved'}
- {'code': 1, 'msg': '密码为空'}
+ {'code': 2,
+  'copyright': 'Copyright 柠檬班 © 2017-2019 湖南省零檬信息技术有限公司 All Rights Reserved',
+  'data': None,
+  'msg': '密码为空'}
Traceback (most recent call last):
  File "E:\project\apitest\testcases\testlogin.py", line 40, in test_login
    self.assertEqual(expected, res)
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 1138, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: {'code': 1, 'msg': '密码为空'} != {'code': 2, 'msg': '密码为空', 'data': None, 'copyrigh[61 chars]ved'}
- {'code': 1, 'msg': '密码为空'}
+ {'code': 2,
+  'copyright': 'Copyright 柠檬班 © 2017-2019 湖南省零檬信息技术有限公司 All Rights Reserved',
+  'data': None,
+  'msg': '密码为空'}
2020-02-23 16:00:16,603 - [testlogin.py-->line:43]- ERROR: 用例不通过
2020-02-23 16:00:16,603 - [testlogin.py-->line:44]- ERROR: {'cod[20 chars]信息错误'} != {'cod[20 chars]信息错误', 'data': None, 'copyright': 'Copyright 柠[45 chars]ved'}
- {'code': 1001, 'msg': '账号信息错误'}
+ {'code': 1001,
+  'copyright': 'Copyright 柠檬班 © 2017-2019 湖南省零檬信息技术有限公司 All Rights Reserved',
+  'data': None,
+  'msg': '账号信息错误'}
Traceback (most recent call last):
  File "E:\project\apitest\testcases\testlogin.py", line 40, in test_login
    self.assertEqual(expected, res)
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 1138, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: {'cod[20 chars]信息错误'} != {'cod[20 chars]信息错误', 'data': None, 'copyright': 'Copyright 柠[45 chars]ved'}
- {'code': 1001, 'msg': '账号信息错误'}
+ {'code': 1001,
+  'copyright': 'Copyright 柠檬班 © 2017-2019 湖南省零檬信息技术有限公司 All Rights Reserved',
+  'data': None,
+  'msg': '账号信息错误'}
2020-02-23 16:00:16,686 - [testlogin.py-->line:43]- ERROR: 用例不通过
2020-02-23 16:00:16,686 - [testlogin.py-->line:44]- ERROR: {'cod[20 chars]信息错误'} != {'cod[20 chars]信息错误', 'data': None, 'copyright': 'Copyright 柠[45 chars]ved'}
- {'code': 1001, 'msg': '账号信息错误'}
+ {'code': 1001,
+  'copyright': 'Copyright 柠檬班 © 2017-2019 湖南省零檬信息技术有限公司 All Rights Reserved',
+  'data': None,
+  'msg': '账号信息错误'}
Traceback (most recent call last):
  File "E:\project\apitest\testcases\testlogin.py", line 40, in test_login
    self.assertEqual(expected, res)
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 1138, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: {'cod[20 chars]信息错误'} != {'cod[20 chars]信息错误', 'data': None, 'copyright': 'Copyright 柠[45 chars]ved'}
- {'code': 1001, 'msg': '账号信息错误'}
+ {'code': 1001,
+  'copyright': 'Copyright 柠檬班 © 2017-2019 湖南省零檬信息技术有限公司 All Rights Reserved',
+  'data': None,
+  'msg': '账号信息错误'}
2020-02-23 16:00:16,767 - [testlogin.py-->line:43]- ERROR: 用例不通过
2020-02-23 16:00:16,767 - [testlogin.py-->line:44]- ERROR: {'cod[18 chars]手机格式'} != {'cod[18 chars]手机格式', 'data': None, 'copyright': 'Copyright 柠[45 chars]ved'}
+ {'code': 2,
+  'copyright': 'Copyright 柠檬班 © 2017-2019 湖南省零檬信息技术有限公司 All Rights Reserved',
+  'data': None,
- {'code': 2, 'msg': '无效的手机格式'}
? -----------

+  'msg': '无效的手机格式'}
Traceback (most recent call last):
  File "E:\project\apitest\testcases\testlogin.py", line 40, in test_login
    self.assertEqual(expected, res)
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 1138, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: {'cod[18 chars]手机格式'} != {'cod[18 chars]手机格式', 'data': None, 'copyright': 'Copyright 柠[45 chars]ved'}
+ {'code': 2,
+  'copyright': 'Copyright 柠檬班 © 2017-2019 湖南省零檬信息技术有限公司 All Rights Reserved',
+  'data': None,
- {'code': 2, 'msg': '无效的手机格式'}
? -----------

+  'msg': '无效的手机格式'}
2020-02-23 16:00:16,911 - [testregister.py-->line:46]- ERROR: 用例不通过
2020-02-23 16:00:16,911 - [testregister.py-->line:47]- ERROR: {'code': 0, 'msg': 'OK'} != {'code': 2, 'msg': '无效的手机格式', 'data': None, 'copyr[64 chars]ved'}
- {'code': 0, 'msg': 'OK'}
+ {'code': 2,
+  'copyright': 'Copyright 柠檬班 © 2017-2019 湖南省零檬信息技术有限公司 All Rights Reserved',
+  'data': None,
+  'msg': '无效的手机格式'}
Traceback (most recent call last):
  File "E:\project\apitest\testcases\testregister.py", line 43, in test_regiter
    self.assertEqual(expected, res)
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 1138, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: {'code': 0, 'msg': 'OK'} != {'code': 2, 'msg': '无效的手机格式', 'data': None, 'copyr[64 chars]ved'}
- {'code': 0, 'msg': 'OK'}
+ {'code': 2,
+  'copyright': 'Copyright 柠檬班 © 2017-2019 湖南省零檬信息技术有限公司 All Rights Reserved',
+  'data': None,
+  'msg': '无效的手机格式'}
2020-02-23 16:00:16,987 - [testregister.py-->line:46]- ERROR: 用例不通过
2020-02-23 16:00:16,987 - [testregister.py-->line:47]- ERROR: {'code': 0, 'msg': 'OK'} != {'code': 2, 'msg': '无效的手机格式', 'data': None, 'copyr[64 chars]ved'}
- {'code': 0, 'msg': 'OK'}
+ {'code': 2,
+  'copyright': 'Copyright 柠檬班 © 2017-2019 湖南省零檬信息技术有限公司 All Rights Reserved',
+  'data': None,
+  'msg': '无效的手机格式'}
Traceback (most recent call last):
  File "E:\project\apitest\testcases\testregister.py", line 43, in test_regiter
    self.assertEqual(expected, res)
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 1138, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: {'code': 0, 'msg': 'OK'} != {'code': 2, 'msg': '无效的手机格式', 'data': None, 'copyr[64 chars]ved'}
- {'code': 0, 'msg': 'OK'}
+ {'code': 2,
+  'copyright': 'Copyright 柠檬班 © 2017-2019 湖南省零檬信息技术有限公司 All Rights Reserved',
+  'data': None,
+  'msg': '无效的手机格式'}
2020-02-23 16:00:17,049 - [testregister.py-->line:46]- ERROR: 用例不通过
2020-02-23 16:00:17,049 - [testregister.py-->line:47]- ERROR: {'cod[16 chars]机号为空'} != {'cod[16 chars]机号为空', 'data': None, 'copyright': 'Copyright 柠[45 chars]ved'}
- {'code': 1, 'msg': '手机号为空'}
+ {'code': 1,
+  'copyright': 'Copyright 柠檬班 © 2017-2019 湖南省零檬信息技术有限公司 All Rights Reserved',
+  'data': None,
+  'msg': '手机号为空'}
Traceback (most recent call last):
  File "E:\project\apitest\testcases\testregister.py", line 43, in test_regiter
    self.assertEqual(expected, res)
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 1138, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: {'cod[16 chars]机号为空'} != {'cod[16 chars]机号为空', 'data': None, 'copyright': 'Copyright 柠[45 chars]ved'}
- {'code': 1, 'msg': '手机号为空'}
+ {'code': 1,
+  'copyright': 'Copyright 柠檬班 © 2017-2019 湖南省零檬信息技术有限公司 All Rights Reserved',
+  'data': None,
+  'msg': '手机号为空'}
2020-02-23 16:00:17,191 - [testregister.py-->line:46]- ERROR: 用例不通过
2020-02-23 16:00:17,191 - [testregister.py-->line:47]- ERROR: {'cod[18 chars]手机格式'} != {'cod[18 chars]手机格式', 'data': None, 'copyright': 'Copyright 柠[45 chars]ved'}
+ {'code': 2,
+  'copyright': 'Copyright 柠檬班 © 2017-2019 湖南省零檬信息技术有限公司 All Rights Reserved',
+  'data': None,
- {'code': 2, 'msg': '无效的手机格式'}
? -----------

+  'msg': '无效的手机格式'}
Traceback (most recent call last):
  File "E:\project\apitest\testcases\testregister.py", line 43, in test_regiter
    self.assertEqual(expected, res)
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 1138, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: {'cod[18 chars]手机格式'} != {'cod[18 chars]手机格式', 'data': None, 'copyright': 'Copyright 柠[45 chars]ved'}
+ {'code': 2,
+  'copyright': 'Copyright 柠檬班 © 2017-2019 湖南省零檬信息技术有限公司 All Rights Reserved',
+  'data': None,
- {'code': 2, 'msg': '无效的手机格式'}
? -----------

+  'msg': '无效的手机格式'}
2020-02-23 16:00:17,256 - [testregister.py-->line:46]- ERROR: 用例不通过
2020-02-23 16:00:17,256 - [testregister.py-->line:47]- ERROR: {'cod[18 chars]手机格式'} != {'cod[18 chars]手机格式', 'data': None, 'copyright': 'Copyright 柠[45 chars]ved'}
+ {'code': 2,
+  'copyright': 'Copyright 柠檬班 © 2017-2019 湖南省零檬信息技术有限公司 All Rights Reserved',
+  'data': None,
- {'code': 2, 'msg': '无效的手机格式'}
? -----------

+  'msg': '无效的手机格式'}
Traceback (most recent call last):
  File "E:\project\apitest\testcases\testregister.py", line 43, in test_regiter
    self.assertEqual(expected, res)
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 1138, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: {'cod[18 chars]手机格式'} != {'cod[18 chars]手机格式', 'data': None, 'copyright': 'Copyright 柠[45 chars]ved'}
+ {'code': 2,
+  'copyright': 'Copyright 柠檬班 © 2017-2019 湖南省零檬信息技术有限公司 All Rights Reserved',
+  'data': None,
- {'code': 2, 'msg': '无效的手机格式'}
? -----------

+  'msg': '无效的手机格式'}
2020-02-23 16:00:17,322 - [testregister.py-->line:46]- ERROR: 用例不通过
2020-02-23 16:00:17,322 - [testregister.py-->line:47]- ERROR: {'cod[18 chars]手机格式'} != {'cod[18 chars]手机格式', 'data': None, 'copyright': 'Copyright 柠[45 chars]ved'}
+ {'code': 2,
+  'copyright': 'Copyright 柠檬班 © 2017-2019 湖南省零檬信息技术有限公司 All Rights Reserved',
+  'data': None,
- {'code': 2, 'msg': '无效的手机格式'}
? -----------

+  'msg': '无效的手机格式'}
Traceback (most recent call last):
  File "E:\project\apitest\testcases\testregister.py", line 43, in test_regiter
    self.assertEqual(expected, res)
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 1138, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: {'cod[18 chars]手机格式'} != {'cod[18 chars]手机格式', 'data': None, 'copyright': 'Copyright 柠[45 chars]ved'}
+ {'code': 2,
+  'copyright': 'Copyright 柠檬班 © 2017-2019 湖南省零檬信息技术有限公司 All Rights Reserved',
+  'data': None,
- {'code': 2, 'msg': '无效的手机格式'}
? -----------

+  'msg': '无效的手机格式'}
2020-02-23 16:00:17,453 - [testregister.py-->line:46]- ERROR: 用例不通过
2020-02-23 16:00:17,453 - [testregister.py-->line:47]- ERROR: {'cod[16 chars]号已存在'} != {'cod[16 chars]号已存在', 'data': None, 'copyright': 'Copyright 柠[45 chars]ved'}
- {'code': 2, 'msg': '账号已存在'}
+ {'code': 2,
+  'copyright': 'Copyright 柠檬班 © 2017-2019 湖南省零檬信息技术有限公司 All Rights Reserved',
+  'data': None,
+  'msg': '账号已存在'}
Traceback (most recent call last):
  File "E:\project\apitest\testcases\testregister.py", line 43, in test_regiter
    self.assertEqual(expected, res)
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 1138, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: {'cod[16 chars]号已存在'} != {'cod[16 chars]号已存在', 'data': None, 'copyright': 'Copyright 柠[45 chars]ved'}
- {'code': 2, 'msg': '账号已存在'}
+ {'code': 2,
+  'copyright': 'Copyright 柠檬班 © 2017-2019 湖南省零檬信息技术有限公司 All Rights Reserved',
+  'data': None,
+  'msg': '账号已存在'}
2020-02-23 16:00:17,526 - [testregister.py-->line:46]- ERROR: 用例不通过
2020-02-23 16:00:17,526 - [testregister.py-->line:47]- ERROR: {'cod[21 chars]到16位'} != {'cod[21 chars]到16位', 'data': None, 'copyright': 'Copyright 柠[45 chars]ved'}
+ {'code': 2,
+  'copyright': 'Copyright 柠檬班 © 2017-2019 湖南省零檬信息技术有限公司 All Rights Reserved',
+  'data': None,
- {'code': 2, 'msg': '密码格式为8到16位'}
? -----------

+  'msg': '密码格式为8到16位'}
Traceback (most recent call last):
  File "E:\project\apitest\testcases\testregister.py", line 43, in test_regiter
    self.assertEqual(expected, res)
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 1138, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: {'cod[21 chars]到16位'} != {'cod[21 chars]到16位', 'data': None, 'copyright': 'Copyright 柠[45 chars]ved'}
+ {'code': 2,
+  'copyright': 'Copyright 柠檬班 © 2017-2019 湖南省零檬信息技术有限公司 All Rights Reserved',
+  'data': None,
- {'code': 2, 'msg': '密码格式为8到16位'}
? -----------

+  'msg': '密码格式为8到16位'}
2020-02-23 16:00:17,596 - [testregister.py-->line:46]- ERROR: 用例不通过
2020-02-23 16:00:17,596 - [testregister.py-->line:47]- ERROR: {'cod[21 chars]到16位'} != {'cod[21 chars]到16位', 'data': None, 'copyright': 'Copyright 柠[45 chars]ved'}
+ {'code': 2,
+  'copyright': 'Copyright 柠檬班 © 2017-2019 湖南省零檬信息技术有限公司 All Rights Reserved',
+  'data': None,
- {'code': 2, 'msg': '密码格式为8到16位'}
? -----------

+  'msg': '密码格式为8到16位'}
Traceback (most recent call last):
  File "E:\project\apitest\testcases\testregister.py", line 43, in test_regiter
    self.assertEqual(expected, res)
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 1138, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: {'cod[21 chars]到16位'} != {'cod[21 chars]到16位', 'data': None, 'copyright': 'Copyright 柠[45 chars]ved'}
+ {'code': 2,
+  'copyright': 'Copyright 柠檬班 © 2017-2019 湖南省零檬信息技术有限公司 All Rights Reserved',
+  'data': None,
- {'code': 2, 'msg': '密码格式为8到16位'}
? -----------

+  'msg': '密码格式为8到16位'}
2020-02-23 16:00:17,680 - [testregister.py-->line:46]- ERROR: 用例不通过
2020-02-23 16:00:17,681 - [testregister.py-->line:47]- ERROR: {'cod[15 chars]密码为空'} != {'cod[15 chars]密码为空', 'data': None, 'copyright': 'Copyright 柠[45 chars]ved'}
- {'code': 1, 'msg': '密码为空'}
+ {'code': 1,
+  'copyright': 'Copyright 柠檬班 © 2017-2019 湖南省零檬信息技术有限公司 All Rights Reserved',
+  'data': None,
+  'msg': '密码为空'}
Traceback (most recent call last):
  File "E:\project\apitest\testcases\testregister.py", line 43, in test_regiter
    self.assertEqual(expected, res)
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 1138, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: {'cod[15 chars]密码为空'} != {'cod[15 chars]密码为空', 'data': None, 'copyright': 'Copyright 柠[45 chars]ved'}
- {'code': 1, 'msg': '密码为空'}
+ {'code': 1,
+  'copyright': 'Copyright 柠檬班 © 2017-2019 湖南省零檬信息技术有限公司 All Rights Reserved',
+  'data': None,
+  'msg': '密码为空'}
2020-02-23 16:00:17,772 - [testregister.py-->line:46]- ERROR: 用例不通过
2020-02-23 16:00:17,772 - [testregister.py-->line:47]- ERROR: {'code': 2, 'msg': '用户昵称长度超过10位'} != {'code': 2, 'msg': '无效的手机格式', 'data': None, 'copyright': 'Cop[53 chars]ved'}
- {'code': 2, 'msg': '用户昵称长度超过10位'}
+ {'code': 2,
+  'copyright': 'Copyright 柠檬班 © 2017-2019 湖南省零檬信息技术有限公司 All Rights Reserved',
+  'data': None,
+  'msg': '无效的手机格式'}
Traceback (most recent call last):
  File "E:\project\apitest\testcases\testregister.py", line 43, in test_regiter
    self.assertEqual(expected, res)
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 1138, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: {'code': 2, 'msg': '用户昵称长度超过10位'} != {'code': 2, 'msg': '无效的手机格式', 'data': None, 'copyright': 'Cop[53 chars]ved'}
- {'code': 2, 'msg': '用户昵称长度超过10位'}
+ {'code': 2,
+  'copyright': 'Copyright 柠檬班 © 2017-2019 湖南省零檬信息技术有限公司 All Rights Reserved',
+  'data': None,
+  'msg': '无效的手机格式'}
2020-02-23 16:00:17,893 - [testregister.py-->line:46]- ERROR: 用例不通过
2020-02-23 16:00:17,894 - [testregister.py-->line:47]- ERROR: {'code': 2, 'msg': '不支持的用户类型'} != {'code': 2, 'msg': '无效的手机格式', 'data': None, 'copyright': 'Cop[53 chars]ved'}
- {'code': 2, 'msg': '不支持的用户类型'}
+ {'code': 2,
+  'copyright': 'Copyright 柠檬班 © 2017-2019 湖南省零檬信息技术有限公司 All Rights Reserved',
+  'data': None,
+  'msg': '无效的手机格式'}
Traceback (most recent call last):
  File "E:\project\apitest\testcases\testregister.py", line 43, in test_regiter
    self.assertEqual(expected, res)
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 1138, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: {'code': 2, 'msg': '不支持的用户类型'} != {'code': 2, 'msg': '无效的手机格式', 'data': None, 'copyright': 'Cop[53 chars]ved'}
- {'code': 2, 'msg': '不支持的用户类型'}
+ {'code': 2,
+  'copyright': 'Copyright 柠檬班 © 2017-2019 湖南省零檬信息技术有限公司 All Rights Reserved',
+  'data': None,
+  'msg': '无效的手机格式'}
2020-02-23 16:00:17,978 - [testregister.py-->line:46]- ERROR: 用例不通过
2020-02-23 16:00:17,978 - [testregister.py-->line:47]- ERROR: {'code': 0, 'msg': 'OK'} != {'code': 2, 'msg': '无效的手机格式', 'data': None, 'copyr[64 chars]ved'}
- {'code': 0, 'msg': 'OK'}
+ {'code': 2,
+  'copyright': 'Copyright 柠檬班 © 2017-2019 湖南省零檬信息技术有限公司 All Rights Reserved',
+  'data': None,
+  'msg': '无效的手机格式'}
Traceback (most recent call last):
  File "E:\project\apitest\testcases\testregister.py", line 43, in test_regiter
    self.assertEqual(expected, res)
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 1138, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: {'code': 0, 'msg': 'OK'} != {'code': 2, 'msg': '无效的手机格式', 'data': None, 'copyr[64 chars]ved'}
- {'code': 0, 'msg': 'OK'}
+ {'code': 2,
+  'copyright': 'Copyright 柠檬班 © 2017-2019 湖南省零檬信息技术有限公司 All Rights Reserved',
+  'data': None,
+  'msg': '无效的手机格式'}
2020-02-23 16:02:59,262 - [testlogin.py-->line:44]- ERROR: 手机号为空用例不通过
2020-02-23 16:02:59,262 - [testlogin.py-->line:45]- ERROR: 1 != 2
Traceback (most recent call last):
  File "E:\project\apitest\testcases\testlogin.py", line 40, in test_login
    self.assertEqual(expected['code'], res['code'])
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-23 16:02:59,320 - [testlogin.py-->line:44]- ERROR: 密码为空用例不通过
2020-02-23 16:02:59,320 - [testlogin.py-->line:45]- ERROR: 1 != 2
Traceback (most recent call last):
  File "E:\project\apitest\testcases\testlogin.py", line 40, in test_login
    self.assertEqual(expected['code'], res['code'])
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-23 16:02:59,583 - [testregister.py-->line:47]- ERROR: 注册成功-带注册名用例不通过
2020-02-23 16:02:59,583 - [testregister.py-->line:48]- ERROR: 0 != 2
Traceback (most recent call last):
  File "E:\project\apitest\testcases\testregister.py", line 43, in test_regiter
    self.assertEqual(expected['code'], res['code'])
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2
2020-02-23 16:02:59,639 - [testregister.py-->line:47]- ERROR: 成功-不带用户名用例不通过
2020-02-23 16:02:59,639 - [testregister.py-->line:48]- ERROR: 0 != 2
Traceback (most recent call last):
  File "E:\project\apitest\testcases\testregister.py", line 43, in test_regiter
    self.assertEqual(expected['code'], res['code'])
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2
2020-02-23 16:03:00,207 - [testregister.py-->line:47]- ERROR: 注册名11位用例不通过
2020-02-23 16:03:00,208 - [testregister.py-->line:48]- ERROR: '用户昵称长度超过10位' != '无效的手机格式'
- 用户昵称长度超过10位
+ 无效的手机格式
Traceback (most recent call last):
  File "E:\project\apitest\testcases\testregister.py", line 44, in test_regiter
    self.assertEqual(expected['msg'], res['msg'])
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '用户昵称长度超过10位' != '无效的手机格式'
- 用户昵称长度超过10位
+ 无效的手机格式

2020-02-23 16:03:00,267 - [testregister.py-->line:47]- ERROR: 类型输入非0，1内容用例不通过
2020-02-23 16:03:00,267 - [testregister.py-->line:48]- ERROR: '不支持的用户类型' != '无效的手机格式'
- 不支持的用户类型
+ 无效的手机格式
Traceback (most recent call last):
  File "E:\project\apitest\testcases\testregister.py", line 44, in test_regiter
    self.assertEqual(expected['msg'], res['msg'])
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '不支持的用户类型' != '无效的手机格式'
- 不支持的用户类型
+ 无效的手机格式

2020-02-23 16:03:00,328 - [testregister.py-->line:47]- ERROR: 不输入类型用例不通过
2020-02-23 16:03:00,329 - [testregister.py-->line:48]- ERROR: 0 != 2
Traceback (most recent call last):
  File "E:\project\apitest\testcases\testregister.py", line 43, in test_regiter
    self.assertEqual(expected['code'], res['code'])
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 2
2020-02-23 16:07:22,437 - [testlogin.py-->line:44]- ERROR: 手机号为空用例不通过
2020-02-23 16:07:22,437 - [testlogin.py-->line:45]- ERROR: 1 != 2
Traceback (most recent call last):
  File "E:\project\apitest\testcases\testlogin.py", line 40, in test_login
    self.assertEqual(expected['code'], res['code'])
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-23 16:07:22,496 - [testlogin.py-->line:44]- ERROR: 密码为空用例不通过
2020-02-23 16:07:22,496 - [testlogin.py-->line:45]- ERROR: 1 != 2
Traceback (most recent call last):
  File "E:\project\apitest\testcases\testlogin.py", line 40, in test_login
    self.assertEqual(expected['code'], res['code'])
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-23 19:07:28,609 - [testlogin.py-->line:44]- ERROR: 手机号为空用例不通过
2020-02-23 19:07:28,610 - [testlogin.py-->line:45]- ERROR: 1 != 2
Traceback (most recent call last):
  File "E:\project\apitest\testcases\testlogin.py", line 40, in test_login
    self.assertEqual(expected['code'], res['code'])
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-23 19:07:28,687 - [testlogin.py-->line:44]- ERROR: 密码为空用例不通过
2020-02-23 19:07:28,687 - [testlogin.py-->line:45]- ERROR: 1 != 2
Traceback (most recent call last):
  File "E:\project\apitest\testcases\testlogin.py", line 40, in test_login
    self.assertEqual(expected['code'], res['code'])
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-23 19:08:26,510 - [testlogin.py-->line:44]- ERROR: 手机号为空用例不通过
2020-02-23 19:08:26,510 - [testlogin.py-->line:45]- ERROR: 1 != 2
Traceback (most recent call last):
  File "E:\project\apitest\testcases\testlogin.py", line 40, in test_login
    self.assertEqual(expected['code'], res['code'])
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-23 19:08:26,598 - [testlogin.py-->line:44]- ERROR: 密码为空用例不通过
2020-02-23 19:08:26,598 - [testlogin.py-->line:45]- ERROR: 1 != 2
Traceback (most recent call last):
  File "E:\project\apitest\testcases\testlogin.py", line 40, in test_login
    self.assertEqual(expected['code'], res['code'])
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-23 19:09:20,651 - [testlogin.py-->line:44]- ERROR: 手机号为空用例不通过
2020-02-23 19:09:20,652 - [testlogin.py-->line:45]- ERROR: 1 != 2
Traceback (most recent call last):
  File "E:\project\apitest\testcases\testlogin.py", line 40, in test_login
    self.assertEqual(expected['code'], res['code'])
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
2020-02-23 19:09:20,742 - [testlogin.py-->line:44]- ERROR: 密码为空用例不通过
2020-02-23 19:09:20,743 - [testlogin.py-->line:45]- ERROR: 1 != 2
Traceback (most recent call last):
  File "E:\project\apitest\testcases\testlogin.py", line 40, in test_login
    self.assertEqual(expected['code'], res['code'])
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\liyaozhi\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 832, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 2
